---
language: node_js
os: linux
dist: xenial
node_js:
  - lts/*
notifications:
  email: false
git:
  quiet: true
branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  - "npm install -g npm@latest"
install:
  - "npm ci"
before_script:
  - "npm run bootstrap"
jobs:
  include:
    - stage: confidence-check
      if: type = push AND branch != master
      name: "Confidence check"
      script: npm test
    - stage: release
      name: "Release"
      if: type = push AND branch = master
      script: skip
      before_deploy:
        - "sh ./scripts/configure-git.sh"
        - "npm config set '//registry.npmjs.org/:_authToken' '${NPM_AUTH_TOKEN}'"
        - "npm run lerna-release-ci"
      deploy:
        - provider: script
          script: "npm run lerna-publish-ci"
          skip_cleanup: true
          on:
            branch: master
