branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
language: node_js
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        script:
          - "npm run lerna:release && npm run lerna:publish"
        skip_cleanup: true
node_js:
  - node
